# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

variables:
  DEFAULT_IMAGE: debian:stable
  EXTRA_DESCRIPTION: ''

# only run for merge requests and tags
include:
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"

default:
  image: ${DEFAULT_IMAGE}
  interruptible: true

cache: &global_cache
  paths:
    - .cache/
    - node_modules/
  key:
    files:
      - package.json
      - package.nw/package.json

build_job:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^(v|test_).*/
  artifacts:
    paths:
      - build/*
  script:
    - export APT_CACHE_DIR=`pwd`/.cache/apt && mkdir -p $APT_CACHE_DIR
    - export NPM_CONFIG_CACHE=`pwd`/.cache/npm && mkdir -p $NPM_CONFIG_CACHE
    - echo $APT_CACHE_DIR $NPM_CONFIG_CACHE
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get -y install npm wine wine32
    - npm install --prefer-offline
    - npm run dist
    - mkdir build
    - (cd package.nw/dist ; mv *.zip *.exe *.7z *.json ../../build)
    - apt-get -y install build-essential devscripts
    - apt-get -y build-dep .
    - dpkg-buildpackage -uc -us
    - mkdir -p build/debian
    - mv ../*.{deb,dsc,buildinfo,tar.xz,changes} build/debian/
    - ls -R `pwd`/.cache

test_job:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  script:
    - export NPM_CONFIG_CACHE=`pwd`/.cache/npm && mkdir -p $NPM_CONFIG_CACHE
    - rm -rf package.nw/dist
    - npm install --prefer-offline
    - npm test

release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^(v|test_).*/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - job: build_job
  script:
    - echo 'Release for $CI_COMMIT_TAG'
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: debian/changelog
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'


# test2:
#   stage: test
#   script:
#     - echo "Do another parallel test here"
#     - echo "For example run a lint test"
#
# deploy1:
#   stage: deploy
#   only:
#     - tags
#   script:
#     - echo "Do your deploy here"
