# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

variables:
  DEFAULT_IMAGE: debian:stable

default:
  image: ${DEFAULT_IMAGE}
  interruptible: true

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
  - export APT_CACHE_DIR=`pwd`/.cache/apt && mkdir -pv $APT_CACHE_DIR
  - export NPM_CONFIG_CACHE=APT_CACHE_DIR=`pwd`/.cache/npm && mkdir -pv $NPM_CONFIG_CACHE
  - dpkg --add-architecture i386
  - apt-get update
  - apt-get -y install npm wine wine32
  - apt-get -y install git dh-make build-essential devscripts lintian diffutils patch quilt
  - apt-get -y build-dep .
  - npm install

# after_script:
#  - echo "After script section"
#  - echo "For example you might do some cleanup here"

build:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - build/*
    expire_in: 1 week
  script:
    - dpkg-buildpackage -uc -us
    - mkdir build build/debian
    - mv ../*.{deb,dsc,buildinfo,tar.xz,changes} build/debian/
    - npm run dist
    - (cd package.nw/dist ; mv *.zip *.exe *.7z *.json ../../build)

test:
   stage: test
   only:
     - branches
   except:
     - master
   script:
     - npm test

# test2:
#   stage: test
#   script:
#     - echo "Do another parallel test here"
#     - echo "For example run a lint test"
#
# deploy1:
#   stage: deploy
#   only:
#     - tags
#   script:
#     - echo "Do your deploy here"
