.TH gridtracker(1)

.SH NAME
.B gridtracker
- an amateur radio companion

.SH SYNOPSIS
.B gridtracker

.SH DESCRIPTION
.B gridtracker
GridTracker is a companion program to WSJT-X/JTDX. It will listen for activity coming from these
programs and display traffic on a map. Additionally, GridTracker has a call roster for filtering
and displaying QSO activity, as well as an extensive logging/lookup/reporting system.

.SH OPTIONS
none

.SH FILES
.TP
.I
/usr/bin/gridtracker
.TP
.I
/usr/share/gridtracker
.TP
.I
/usr/share/applications/gridtracker.desktop
.TP
.I
$HOME/Documents/GridTracker
.TP
.I
$HOME/.config/gridtracker

.SH EXAMPLES
.TP
.BI gridtracker
.TP
.PP
Run gridtracker, no arguments needed.

.SH COPYRIGHT
.PP
Copyright (c) 2018-2020 Stephen Tag Loomis. All rights reserved.
Copyright (c) 2020-2022 GridTracker.org. All rights reserved.
Released under BSD 3-Clause License
https://gridtracker.org

.SH
.PP
GridTracker.org gridtracker(1)
